// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xcQONarAUzJ1Q1tutWXyg8jo3DbbBWs',
    appId: '1:903749104232:web:86f7fc5743b40baf0ac1dd',
    messagingSenderId: '903749104232',
    projectId: 'skillsync-27e24',
    authDomain: 'skillsync-27e24.firebaseapp.com',
    storageBucket: 'skillsync-27e24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoPtKewRSlTYjV6tMpySxsLHeS5_TNFtM',
    appId: '1:903749104232:android:f785c32d1fcf5d370ac1dd',
    messagingSenderId: '903749104232',
    projectId: 'skillsync-27e24',
    storageBucket: 'skillsync-27e24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb_TJAhM_a6-WXInY52Dhn6KraAPwDpDw',
    appId: '1:903749104232:ios:5ba6be1875ac91940ac1dd',
    messagingSenderId: '903749104232',
    projectId: 'skillsync-27e24',
    storageBucket: 'skillsync-27e24.firebasestorage.app',
    iosBundleId: 'com.example.skillsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb_TJAhM_a6-WXInY52Dhn6KraAPwDpDw',
    appId: '1:903749104232:ios:5ba6be1875ac91940ac1dd',
    messagingSenderId: '903749104232',
    projectId: 'skillsync-27e24',
    storageBucket: 'skillsync-27e24.firebasestorage.app',
    iosBundleId: 'com.example.skillsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1xcQONarAUzJ1Q1tutWXyg8jo3DbbBWs',
    appId: '1:903749104232:web:c37a041eebe654070ac1dd',
    messagingSenderId: '903749104232',
    projectId: 'skillsync-27e24',
    authDomain: 'skillsync-27e24.firebaseapp.com',
    storageBucket: 'skillsync-27e24.firebasestorage.app',
  );
}
